id: P006713
initial_creation_type: ocr
source_metadata:
  id: bdr:W29015
  title: གསུང་འབུམ། བཟང་པོ་བཀྲ་ཤིས
  author: ''
  volumes:
    48c5d2c93b3b46adb781940fbab887cf:
      image_group_id: I5014
      title: ''
      volume_number: 1
      total_pages: 700
